### PR TITLE
Sync with upstream rev 305, 2018-05-23T11:41:34+0200 

### PR DESCRIPTION
**Pull request by Kaiepi**
Updates dyncall from rev 269 (2017-05-27):
http://hg.dyncall.org/pub/dyncall/dyncall/rev/3581366858a6
    
To rev 305 (2018-05-23):
http://hg.dyncall.org/pub/dyncall/dyncall/rev/b104c5beec8b
    
Fixes https://github.com/MoarVM/MoarVM/issues/794
Fixes https://github.com/MoarVM/MoarVM/issues/470

### CODE REVIEW

**Comment by thorsteneb** [comment]
This updates some of the dyncall code, but leaves a good deal of the fixes in dyncall 1.0 out. One of which I care in particular about as it fixes https://github.com/MoarVM/MoarVM/issues/470.  Dyncall 1.0 was released a month+ after this attempt, on 2018-04-23.

Do you have cycles to refresh this with dyncall 1.0? Alternatively, I'm happy to fork MoarVM and bring the new dyncall in.

**Comment by Kaiepi** [comment]
Updated.

> Do you have cycles to refresh this with dyncall 1.0?

I don't have anything set up to do it automatically at the moment. I just pull manually from dyncall's Mercurial repo.

**Comment by deven** [comment]
I was able to build the dyncall-1.0.tar.gz release separately and install it to /usr/local first, then build MoarVM with --has-dyncall to use the dyncall 1.0 library instead of its own copy.  This way the build completes successfully on WSL instead of getting the execstack error, and running the nqp test suite reports "All tests successful", so it seems to work.

Can you just drop in the entire dyncall 1.0 release rather than pulling from their repo?  (A release version might be more stable than the most recent development version anyhow!)

**Comment by deven** [comment]
I can confirm that this update fixes issue #470, although I had to do a "git checkout master" before the build got to this library to use the newest one.

**Pull request merged**
